<?php
/** @var Amasty\SnitkoArtur\Block\Form $block */
?>

<form name="form" class="<?= $block->getData("main.form") ?>">
    <input type="text" class="<?= $block->getData("form.sku") ?>"  name="sku">
    <input type="text" class="<?= $block->getData("form.qty") ?>" name="qty">
    <div>
        <?= $block->getChildHtml('Amasty_SnitkoArtur.additional')?>
    </div>
    <button class="<?= $block->getData("form.btn") ?>">Submit</button>
</form>
