<?php
/** @var Amasty\SnitkoArtur\Block\Form $block */
?>

<form name="form" method="get" action="<?= $block->getFormAction() ?>" class="<?= $block->getData("main.form") ?>"
      data-mage-init='{"validation":{
          "rules":{
            "sku":{
                "required":true
            },
            "qty":{
                "required":true,
                "validate-greater-than-zero":true
            }
          }
      }}'>

    <div class="form-sku-wrapper" data-bind="scope: 'autocomplete'">
    <!--ko template: getTemplate()--><!--/ko-->
    </div>

    <?php if($block->isQtyEnabled()) { ?>
        <input type="text" class="<?= $block->getData("form.qty") ?>" name="qty" id="qty" value="<?= $block->getQtyNumber() ?>">
    <?php }; ?>

    <div>
        <?= $block->getChildHtml('Amasty_SnitkoArtur.additional')?>
    </div>
    <button class="<?= $block->getData("form.btn") ?>">Submit</button>
</form>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "autocomplete": {
                        "component": "Amasty_SnitkoArtur/js/koAutocomplete",
                        "template": "Amasty_SnitkoArtur/koAutocomplete"
                    }
                }
            }
        }
    }
</script>
